# Generated by Django 4.1.7 on 2023-04-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
