# Generated by Django 4.1.7 on 2023-04-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
