# Generated by Django 4.1.7 on 2023-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_participant_date_joined'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user'),
        ),
    ]
