# Generated by Django 4.1.7 on 2023-05-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_settings_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='scan_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
