# Generated by Django 4.1.7 on 2023-02-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_participant_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
