# Generated by Django 4.1.7 on 2023-02-18 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_participant_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
