# Generated by Django 4.1.7 on 2023-02-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_participant_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
