# Generated by Django 4.1.7 on 2023-02-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_participant_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='date_joined',
            new_name='date_participated',
        ),
    ]
