# Generated by Django 4.1.7 on 2023-02-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_rename_date_joined_participant_date_participated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
