# Generated by Django 4.1.7 on 2023-04-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCalendar',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
            ],
            bases=('events.event',),
        ),
    ]
