# Generated by Django 4.1.7 on 2023-04-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventcalendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCalendar',
        ),
    ]
